# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CodeTest' do
pod 'SnapKit', '~> 0.16.0'
pod 'Argo', '~> 2.2.0'
pod 'Curry', '~> 1.4.0'
pod 'ObjectMapper', '~> 1.1'
end

target 'CodeTestTests' do

end

target 'CodeTestUITests' do

end

